name: healio
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  collection: 1.19.1
  dropdown_button2: 2.3.9
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  provider: 6.1.2
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  substring_highlight: 1.0.33
  table_calendar: 3.1.1
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/vectors/

  fonts:
      - family: Notosans
        fonts:
          - asset: assets/fonts/Notosans-Regular.ttf
          - asset: assets/fonts/Notosans-Italic.ttf
            weight: 500
          - asset: assets/fonts/Notosans-Bold.ttf
            weight: 700
          - asset: assets/fonts/Notosans-BoldItalic.ttf
            weight: 900

      - family: Notoserif
        fonts:
           - asset: assets/fonts/Notoserif-Regular.ttf
           -  asset: assets/fonts/Notoserif-Italic.ttf
              weight: 500
           - asset: assets/fonts/Notoserif-Bold.ttf
             weight: 700
           - asset: assets/fonts/Notoserif-BoldItalic.ttf
             weight: 900 